#############################################################################
# Makefile for building: QoS_trace
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  QoS_trace.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile QoS_trace.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I. -Iheader -I./header/unix-gcc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QoS_trace1.0.0
DISTDIR = /home/bmouraz/Documents/GIT/.tmp/QoS_trace1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = source/xlsxabstractooxmlfile.cpp \
		source/xlsxabstractsheet.cpp \
		source/xlsxcell.cpp \
		source/xlsxcellformula.cpp \
		source/xlsxcelllocation.cpp \
		source/xlsxcellrange.cpp \
		source/xlsxcellreference.cpp \
		source/xlsxchart.cpp \
		source/xlsxchartsheet.cpp \
		source/xlsxcolor.cpp \
		source/xlsxconditionalformatting.cpp \
		source/xlsxcontenttypes.cpp \
		source/xlsxdatavalidation.cpp \
		source/xlsxdatetype.cpp \
		source/xlsxdocpropsapp.cpp \
		source/xlsxdocpropscore.cpp \
		source/xlsxdocument.cpp \
		source/xlsxdrawing.cpp \
		source/xlsxdrawinganchor.cpp \
		source/xlsxformat.cpp \
		source/xlsxmediafile.cpp \
		source/xlsxnumformatparser.cpp \
		source/xlsxrelationships.cpp \
		source/xlsxrichstring.cpp \
		source/xlsxsharedstrings.cpp \
		source/xlsxsimpleooxmlfile.cpp \
		source/xlsxstyles.cpp \
		source/xlsxtheme.cpp \
		source/xlsxutility.cpp \
		source/xlsxworkbook.cpp \
		source/xlsxworksheet.cpp \
		source/xlsxzipreader.cpp \
		source/xlsxzipwriter.cpp \
		analyzer.cpp \
		axis_inputdialog.cpp \
		customlinesdialog.cpp \
		inputicksdialog.cpp \
		main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp \
		table_dialog.cpp qrc_resources.cpp \
		moc_xlsxdocument.cpp \
		moc_axis_inputdialog.cpp \
		moc_customlinesdialog.cpp \
		moc_inputicksdialog.cpp \
		moc_mainwindow.cpp \
		moc_qcustomplot.cpp \
		moc_table_dialog.cpp
OBJECTS       = xlsxabstractooxmlfile.o \
		xlsxabstractsheet.o \
		xlsxcell.o \
		xlsxcellformula.o \
		xlsxcelllocation.o \
		xlsxcellrange.o \
		xlsxcellreference.o \
		xlsxchart.o \
		xlsxchartsheet.o \
		xlsxcolor.o \
		xlsxconditionalformatting.o \
		xlsxcontenttypes.o \
		xlsxdatavalidation.o \
		xlsxdatetype.o \
		xlsxdocpropsapp.o \
		xlsxdocpropscore.o \
		xlsxdocument.o \
		xlsxdrawing.o \
		xlsxdrawinganchor.o \
		xlsxformat.o \
		xlsxmediafile.o \
		xlsxnumformatparser.o \
		xlsxrelationships.o \
		xlsxrichstring.o \
		xlsxsharedstrings.o \
		xlsxsimpleooxmlfile.o \
		xlsxstyles.o \
		xlsxtheme.o \
		xlsxutility.o \
		xlsxworkbook.o \
		xlsxworksheet.o \
		xlsxzipreader.o \
		xlsxzipwriter.o \
		analyzer.o \
		axis_inputdialog.o \
		customlinesdialog.o \
		inputicksdialog.o \
		main.o \
		mainwindow.o \
		qcustomplot.o \
		table_dialog.o \
		qrc_resources.o \
		moc_xlsxdocument.o \
		moc_axis_inputdialog.o \
		moc_customlinesdialog.o \
		moc_inputicksdialog.o \
		moc_mainwindow.o \
		moc_qcustomplot.o \
		moc_table_dialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		QXlsx.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		QoS_trace.pro header/xlsxabstractooxmlfile.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractsheet_p.h \
		header/xlsxcell.h \
		header/xlsxcellformula.h \
		header/xlsxcellformula_p.h \
		header/xlsxcelllocation.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcell_p.h \
		header/xlsxchart.h \
		header/xlsxchartsheet.h \
		header/xlsxchartsheet_p.h \
		header/xlsxchart_p.h \
		header/xlsxcolor_p.h \
		header/xlsxconditionalformatting.h \
		header/xlsxconditionalformatting_p.h \
		header/xlsxcontenttypes_p.h \
		header/xlsxdatavalidation.h \
		header/xlsxdatavalidation_p.h \
		header/xlsxdatetype.h \
		header/xlsxdocpropsapp_p.h \
		header/xlsxdocpropscore_p.h \
		header/xlsxdocument.h \
		header/xlsxdocument_p.h \
		header/xlsxdrawinganchor_p.h \
		header/xlsxdrawing_p.h \
		header/xlsxformat.h \
		header/xlsxformat_p.h \
		header/xlsxglobal.h \
		header/xlsxmediafile_p.h \
		header/xlsxnumformatparser_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxrichstring.h \
		header/xlsxrichstring_p.h \
		header/xlsxsharedstrings_p.h \
		header/xlsxsimpleooxmlfile_p.h \
		header/xlsxstyles_p.h \
		header/xlsxtheme_p.h \
		header/xlsxutility_p.h \
		header/xlsxworkbook.h \
		header/xlsxworkbook_p.h \
		header/xlsxworksheet.h \
		header/xlsxworksheet_p.h \
		header/xlsxzipreader_p.h \
		header/xlsxzipwriter_p.h \
		analyzer.h \
		axis_inputdialog.h \
		customlinesdialog.h \
		inputicksdialog.h \
		mainwindow.h \
		qcustomplot.h \
		table_dialog.h source/xlsxabstractooxmlfile.cpp \
		source/xlsxabstractsheet.cpp \
		source/xlsxcell.cpp \
		source/xlsxcellformula.cpp \
		source/xlsxcelllocation.cpp \
		source/xlsxcellrange.cpp \
		source/xlsxcellreference.cpp \
		source/xlsxchart.cpp \
		source/xlsxchartsheet.cpp \
		source/xlsxcolor.cpp \
		source/xlsxconditionalformatting.cpp \
		source/xlsxcontenttypes.cpp \
		source/xlsxdatavalidation.cpp \
		source/xlsxdatetype.cpp \
		source/xlsxdocpropsapp.cpp \
		source/xlsxdocpropscore.cpp \
		source/xlsxdocument.cpp \
		source/xlsxdrawing.cpp \
		source/xlsxdrawinganchor.cpp \
		source/xlsxformat.cpp \
		source/xlsxmediafile.cpp \
		source/xlsxnumformatparser.cpp \
		source/xlsxrelationships.cpp \
		source/xlsxrichstring.cpp \
		source/xlsxsharedstrings.cpp \
		source/xlsxsimpleooxmlfile.cpp \
		source/xlsxstyles.cpp \
		source/xlsxtheme.cpp \
		source/xlsxutility.cpp \
		source/xlsxworkbook.cpp \
		source/xlsxworksheet.cpp \
		source/xlsxzipreader.cpp \
		source/xlsxzipwriter.cpp \
		analyzer.cpp \
		axis_inputdialog.cpp \
		customlinesdialog.cpp \
		inputicksdialog.cpp \
		main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp \
		table_dialog.cpp
QMAKE_TARGET  = QoS_trace
DESTDIR       = 
TARGET        = QoS_trace


first: all
####### Build rules

QoS_trace: ui_axis_inputdialog.h ui_customlinesdialog.h ui_inputicksdialog.h ui_mainwindow.h ui_table_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QoS_trace.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		QXlsx.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		QoS_trace.pro \
		resources.qrc
	$(QMAKE) -o Makefile QoS_trace.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
QXlsx.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
QoS_trace.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile QoS_trace.pro

qmake_all: FORCE


all: Makefile QoS_trace

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents header/xlsxabstractooxmlfile.h header/xlsxabstractooxmlfile_p.h header/xlsxabstractsheet.h header/xlsxabstractsheet_p.h header/xlsxcell.h header/xlsxcellformula.h header/xlsxcellformula_p.h header/xlsxcelllocation.h header/xlsxcellrange.h header/xlsxcellreference.h header/xlsxcell_p.h header/xlsxchart.h header/xlsxchartsheet.h header/xlsxchartsheet_p.h header/xlsxchart_p.h header/xlsxcolor_p.h header/xlsxconditionalformatting.h header/xlsxconditionalformatting_p.h header/xlsxcontenttypes_p.h header/xlsxdatavalidation.h header/xlsxdatavalidation_p.h header/xlsxdatetype.h header/xlsxdocpropsapp_p.h header/xlsxdocpropscore_p.h header/xlsxdocument.h header/xlsxdocument_p.h header/xlsxdrawinganchor_p.h header/xlsxdrawing_p.h header/xlsxformat.h header/xlsxformat_p.h header/xlsxglobal.h header/xlsxmediafile_p.h header/xlsxnumformatparser_p.h header/xlsxrelationships_p.h header/xlsxrichstring.h header/xlsxrichstring_p.h header/xlsxsharedstrings_p.h header/xlsxsimpleooxmlfile_p.h header/xlsxstyles_p.h header/xlsxtheme_p.h header/xlsxutility_p.h header/xlsxworkbook.h header/xlsxworkbook_p.h header/xlsxworksheet.h header/xlsxworksheet_p.h header/xlsxzipreader_p.h header/xlsxzipwriter_p.h analyzer.h axis_inputdialog.h customlinesdialog.h inputicksdialog.h mainwindow.h qcustomplot.h table_dialog.h $(DISTDIR)/
	$(COPY_FILE) --parents source/xlsxabstractooxmlfile.cpp source/xlsxabstractsheet.cpp source/xlsxcell.cpp source/xlsxcellformula.cpp source/xlsxcelllocation.cpp source/xlsxcellrange.cpp source/xlsxcellreference.cpp source/xlsxchart.cpp source/xlsxchartsheet.cpp source/xlsxcolor.cpp source/xlsxconditionalformatting.cpp source/xlsxcontenttypes.cpp source/xlsxdatavalidation.cpp source/xlsxdatetype.cpp source/xlsxdocpropsapp.cpp source/xlsxdocpropscore.cpp source/xlsxdocument.cpp source/xlsxdrawing.cpp source/xlsxdrawinganchor.cpp source/xlsxformat.cpp source/xlsxmediafile.cpp source/xlsxnumformatparser.cpp source/xlsxrelationships.cpp source/xlsxrichstring.cpp source/xlsxsharedstrings.cpp source/xlsxsimpleooxmlfile.cpp source/xlsxstyles.cpp source/xlsxtheme.cpp source/xlsxutility.cpp source/xlsxworkbook.cpp source/xlsxworksheet.cpp source/xlsxzipreader.cpp source/xlsxzipwriter.cpp analyzer.cpp axis_inputdialog.cpp customlinesdialog.cpp inputicksdialog.cpp main.cpp mainwindow.cpp qcustomplot.cpp table_dialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents axis_inputdialog.ui customlinesdialog.ui inputicksdialog.ui mainwindow.ui table_dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		images/icon/open-file.png \
		images/icon/save.png \
		images/icon/Parallelogon_rectangle.png \
		images/icon/edit_graph.png \
		images/icon/save_image.png \
		images/lines/line-dash.png \
		images/lines/line-dashdotdot.png \
		images/lines/line-dot.png \
		images/lines/line-dashdot.png \
		images/lines/line-solid.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_xlsxdocument.cpp moc_axis_inputdialog.cpp moc_customlinesdialog.cpp moc_inputicksdialog.cpp moc_mainwindow.cpp moc_qcustomplot.cpp moc_table_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_xlsxdocument.cpp moc_axis_inputdialog.cpp moc_customlinesdialog.cpp moc_inputicksdialog.cpp moc_mainwindow.cpp moc_qcustomplot.cpp moc_table_dialog.cpp
moc_xlsxdocument.cpp: header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include header/xlsxdocument.h -o moc_xlsxdocument.cpp

moc_axis_inputdialog.cpp: axis_inputdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include axis_inputdialog.h -o moc_axis_inputdialog.cpp

moc_customlinesdialog.cpp: customlinesdialog.h \
		qcustomplot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include customlinesdialog.h -o moc_customlinesdialog.cpp

moc_inputicksdialog.cpp: inputicksdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include inputicksdialog.h -o moc_inputicksdialog.cpp

moc_mainwindow.cpp: mainwindow.h \
		customlinesdialog.h \
		qcustomplot.h \
		axis_inputdialog.h \
		inputicksdialog.h \
		analyzer.h \
		header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxchart.h \
		header/xlsxrichstring.h \
		header/xlsxworkbook.h \
		table_dialog.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_qcustomplot.cpp: qcustomplot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

moc_table_dialog.cpp: table_dialog.h \
		mainwindow.h \
		customlinesdialog.h \
		qcustomplot.h \
		axis_inputdialog.h \
		inputicksdialog.h \
		analyzer.h \
		header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxchart.h \
		header/xlsxrichstring.h \
		header/xlsxworkbook.h \
		table_dialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bmouraz/Documents/GIT/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT -I/home/bmouraz/Documents/GIT/header -I/home/bmouraz/Documents/GIT/header/unix-gcc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include table_dialog.h -o moc_table_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_axis_inputdialog.h ui_customlinesdialog.h ui_inputicksdialog.h ui_mainwindow.h ui_table_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_axis_inputdialog.h ui_customlinesdialog.h ui_inputicksdialog.h ui_mainwindow.h ui_table_dialog.h
ui_axis_inputdialog.h: axis_inputdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic axis_inputdialog.ui -o ui_axis_inputdialog.h

ui_customlinesdialog.h: customlinesdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic customlinesdialog.ui -o ui_customlinesdialog.h

ui_inputicksdialog.h: inputicksdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic inputicksdialog.ui -o ui_inputicksdialog.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		qcustomplot.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_table_dialog.h: table_dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic table_dialog.ui -o ui_table_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

xlsxabstractooxmlfile.o: source/xlsxabstractooxmlfile.cpp header/xlsxabstractooxmlfile.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxrelationships_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxabstractooxmlfile.o source/xlsxabstractooxmlfile.cpp

xlsxabstractsheet.o: source/xlsxabstractsheet.cpp header/xlsxabstractsheet.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxabstractsheet_p.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxdrawing_p.h \
		header/xlsxworkbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxabstractsheet.o source/xlsxabstractsheet.cpp

xlsxcell.o: source/xlsxcell.cpp header/xlsxcell.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxcell_p.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxrichstring.h \
		header/xlsxcellformula.h \
		header/xlsxformat_p.h \
		header/xlsxutility_p.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcelllocation.h \
		header/xlsxworkbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcell.o source/xlsxcell.cpp

xlsxcellformula.o: source/xlsxcellformula.cpp header/xlsxcellformula.h \
		header/xlsxglobal.h \
		header/xlsxcellformula_p.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxutility_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcellformula.o source/xlsxcellformula.cpp

xlsxcelllocation.o: source/xlsxcelllocation.cpp header/xlsxglobal.h \
		header/xlsxcell.h \
		header/xlsxformat.h \
		header/xlsxcelllocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcelllocation.o source/xlsxcelllocation.cpp

xlsxcellrange.o: source/xlsxcellrange.cpp header/xlsxcellrange.h \
		header/xlsxglobal.h \
		header/xlsxcellreference.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcellrange.o source/xlsxcellrange.cpp

xlsxcellreference.o: source/xlsxcellreference.cpp header/xlsxcellreference.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcellreference.o source/xlsxcellreference.cpp

xlsxchart.o: source/xlsxchart.cpp header/xlsxchart_p.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxrelationships_p.h \
		header/xlsxchart.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxcell.h \
		header/xlsxformat.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxutility_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxchart.o source/xlsxchart.cpp

xlsxchartsheet.o: source/xlsxchartsheet.cpp header/xlsxchartsheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxchartsheet_p.h \
		header/xlsxabstractsheet_p.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxdrawing_p.h \
		header/xlsxworkbook.h \
		header/xlsxutility_p.h \
		header/xlsxdrawinganchor_p.h \
		header/xlsxchart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxchartsheet.o source/xlsxchartsheet.cpp

xlsxcolor.o: source/xlsxcolor.cpp header/xlsxcolor_p.h \
		header/xlsxglobal.h \
		header/xlsxstyles_p.h \
		header/xlsxformat.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxutility_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcolor.o source/xlsxcolor.cpp

xlsxconditionalformatting.o: source/xlsxconditionalformatting.cpp header/xlsxconditionalformatting.h \
		header/xlsxglobal.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxconditionalformatting_p.h \
		header/xlsxformat.h \
		header/xlsxcolor_p.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcelllocation.h \
		header/xlsxstyles_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxconditionalformatting.o source/xlsxconditionalformatting.cpp

xlsxcontenttypes.o: source/xlsxcontenttypes.cpp header/xlsxcontenttypes_p.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxcontenttypes.o source/xlsxcontenttypes.cpp

xlsxdatavalidation.o: source/xlsxdatavalidation.cpp header/xlsxdatavalidation.h \
		header/xlsxglobal.h \
		header/xlsxdatavalidation_p.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxformat.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdatavalidation.o source/xlsxdatavalidation.cpp

xlsxdatetype.o: source/xlsxdatetype.cpp header/xlsxglobal.h \
		header/xlsxutility_p.h \
		header/xlsxdatetype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdatetype.o source/xlsxdatetype.cpp

xlsxdocpropsapp.o: source/xlsxdocpropsapp.cpp header/xlsxdocpropsapp_p.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdocpropsapp.o source/xlsxdocpropsapp.cpp

xlsxdocpropscore.o: source/xlsxdocpropscore.cpp header/xlsxdocpropscore_p.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdocpropscore.o source/xlsxdocpropscore.cpp

xlsxdocument.o: source/xlsxdocument.cpp header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxdocument_p.h \
		header/xlsxworkbook.h \
		header/xlsxcontenttypes_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxstyles_p.h \
		header/xlsxtheme_p.h \
		header/xlsxdocpropsapp_p.h \
		header/xlsxdocpropscore_p.h \
		header/xlsxsharedstrings_p.h \
		header/xlsxrichstring.h \
		header/xlsxutility_p.h \
		header/xlsxworkbook_p.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxsimpleooxmlfile_p.h \
		header/xlsxdrawing_p.h \
		header/xlsxmediafile_p.h \
		header/xlsxchart.h \
		header/xlsxzipreader_p.h \
		header/xlsxzipwriter_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdocument.o source/xlsxdocument.cpp

xlsxdrawing.o: source/xlsxdrawing.cpp header/xlsxdrawing_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxdrawinganchor_p.h \
		header/xlsxabstractsheet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdrawing.o source/xlsxdrawing.cpp

xlsxdrawinganchor.o: source/xlsxdrawinganchor.cpp header/xlsxdrawinganchor_p.h \
		header/xlsxglobal.h \
		header/xlsxdrawing_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxmediafile_p.h \
		header/xlsxchart.h \
		header/xlsxworkbook.h \
		header/xlsxabstractsheet.h \
		header/xlsxutility_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxdrawinganchor.o source/xlsxdrawinganchor.cpp

xlsxformat.o: source/xlsxformat.cpp header/xlsxformat.h \
		header/xlsxglobal.h \
		header/xlsxformat_p.h \
		header/xlsxcolor_p.h \
		header/xlsxnumformatparser_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxformat.o source/xlsxformat.cpp

xlsxmediafile.o: source/xlsxmediafile.cpp header/xlsxmediafile_p.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxmediafile.o source/xlsxmediafile.cpp

xlsxnumformatparser.o: source/xlsxnumformatparser.cpp header/xlsxnumformatparser_p.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxnumformatparser.o source/xlsxnumformatparser.cpp

xlsxrelationships.o: source/xlsxrelationships.cpp header/xlsxrelationships_p.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxrelationships.o source/xlsxrelationships.cpp

xlsxrichstring.o: source/xlsxrichstring.cpp header/xlsxrichstring.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxrichstring_p.h \
		header/xlsxformat_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxrichstring.o source/xlsxrichstring.cpp

xlsxsharedstrings.o: source/xlsxsharedstrings.cpp header/xlsxrichstring.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxsharedstrings_p.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxutility_p.h \
		header/xlsxformat_p.h \
		header/xlsxcolor_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxsharedstrings.o source/xlsxsharedstrings.cpp

xlsxsimpleooxmlfile.o: source/xlsxsimpleooxmlfile.cpp header/xlsxsimpleooxmlfile_p.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxsimpleooxmlfile.o source/xlsxsimpleooxmlfile.cpp

xlsxstyles.o: source/xlsxstyles.cpp header/xlsxglobal.h \
		header/xlsxstyles_p.h \
		header/xlsxformat.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxformat_p.h \
		header/xlsxutility_p.h \
		header/xlsxcolor_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxstyles.o source/xlsxstyles.cpp

xlsxtheme.o: source/xlsxtheme.cpp header/xlsxtheme_p.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxtheme.o source/xlsxtheme.cpp

xlsxutility.o: source/xlsxutility.cpp header/xlsxutility_p.h \
		header/xlsxglobal.h \
		header/xlsxcellreference.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxutility.o source/xlsxutility.cpp

xlsxworkbook.o: source/xlsxworkbook.cpp header/xlsxworkbook.h \
		header/xlsxglobal.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxabstractsheet.h \
		header/xlsxworkbook_p.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxtheme_p.h \
		header/xlsxsimpleooxmlfile_p.h \
		header/xlsxsharedstrings_p.h \
		header/xlsxrichstring.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxstyles_p.h \
		header/xlsxworksheet_p.h \
		header/xlsxabstractsheet_p.h \
		header/xlsxdrawing_p.h \
		header/xlsxdatavalidation.h \
		header/xlsxconditionalformatting.h \
		header/xlsxcellformula.h \
		header/xlsxformat_p.h \
		header/xlsxmediafile_p.h \
		header/xlsxutility_p.h \
		header/xlsxchart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxworkbook.o source/xlsxworkbook.cpp

xlsxworksheet.o: source/xlsxworksheet.cpp header/xlsxrichstring.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxcellreference.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcelllocation.h \
		header/xlsxworksheet_p.h \
		header/xlsxabstractsheet_p.h \
		header/xlsxabstractooxmlfile_p.h \
		header/xlsxrelationships_p.h \
		header/xlsxdrawing_p.h \
		header/xlsxdatavalidation.h \
		header/xlsxconditionalformatting.h \
		header/xlsxcellformula.h \
		header/xlsxworkbook.h \
		header/xlsxformat_p.h \
		header/xlsxutility_p.h \
		header/xlsxsharedstrings_p.h \
		header/xlsxstyles_p.h \
		header/xlsxcell_p.h \
		header/xlsxconditionalformatting_p.h \
		header/xlsxcolor_p.h \
		header/xlsxdrawinganchor_p.h \
		header/xlsxchart.h \
		header/xlsxcellformula_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxworksheet.o source/xlsxworksheet.cpp

xlsxzipreader.o: source/xlsxzipreader.cpp header/xlsxzipreader_p.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxzipreader.o source/xlsxzipreader.cpp

xlsxzipwriter.o: source/xlsxzipwriter.cpp header/xlsxzipwriter_p.h \
		header/xlsxglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsxzipwriter.o source/xlsxzipwriter.cpp

analyzer.o: analyzer.cpp analyzer.h \
		header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxchart.h \
		header/xlsxrichstring.h \
		header/xlsxworkbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analyzer.o analyzer.cpp

axis_inputdialog.o: axis_inputdialog.cpp axis_inputdialog.h \
		ui_axis_inputdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o axis_inputdialog.o axis_inputdialog.cpp

customlinesdialog.o: customlinesdialog.cpp customlinesdialog.h \
		qcustomplot.h \
		ui_customlinesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customlinesdialog.o customlinesdialog.cpp

inputicksdialog.o: inputicksdialog.cpp inputicksdialog.h \
		ui_inputicksdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputicksdialog.o inputicksdialog.cpp

main.o: main.cpp mainwindow.h \
		customlinesdialog.h \
		qcustomplot.h \
		axis_inputdialog.h \
		inputicksdialog.h \
		analyzer.h \
		header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxchart.h \
		header/xlsxrichstring.h \
		header/xlsxworkbook.h \
		table_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		customlinesdialog.h \
		qcustomplot.h \
		axis_inputdialog.h \
		inputicksdialog.h \
		analyzer.h \
		header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxchart.h \
		header/xlsxrichstring.h \
		header/xlsxworkbook.h \
		table_dialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

table_dialog.o: table_dialog.cpp table_dialog.h \
		mainwindow.h \
		customlinesdialog.h \
		qcustomplot.h \
		axis_inputdialog.h \
		inputicksdialog.h \
		analyzer.h \
		header/xlsxdocument.h \
		header/xlsxglobal.h \
		header/xlsxformat.h \
		header/xlsxworksheet.h \
		header/xlsxabstractsheet.h \
		header/xlsxabstractooxmlfile.h \
		header/xlsxcell.h \
		header/xlsxcellrange.h \
		header/xlsxcellreference.h \
		header/xlsxcelllocation.h \
		header/xlsxchartsheet.h \
		header/xlsxchart.h \
		header/xlsxrichstring.h \
		header/xlsxworkbook.h \
		ui_table_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table_dialog.o table_dialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_xlsxdocument.o: moc_xlsxdocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xlsxdocument.o moc_xlsxdocument.cpp

moc_axis_inputdialog.o: moc_axis_inputdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_axis_inputdialog.o moc_axis_inputdialog.cpp

moc_customlinesdialog.o: moc_customlinesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customlinesdialog.o moc_customlinesdialog.cpp

moc_inputicksdialog.o: moc_inputicksdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputicksdialog.o moc_inputicksdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_table_dialog.o: moc_table_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_table_dialog.o moc_table_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QoS_trace/bin || mkdir -p $(INSTALL_ROOT)/opt/QoS_trace/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/QoS_trace/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/QoS_trace/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/QoS_trace/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QoS_trace/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

